/**
 * The Golden Path Integration pipeline generator (bonus).
 *
 * Triggered when code merges into `main`. It runs final validation and then
 * deploys to Production via CDK — reusing the exact same job builders as the PR
 * pipeline, so the two pipelines stay consistent and DORA stays continuous
 * across both (same event schema on every deploy).
 */

import { Workflow } from "github-actions-workflow-ts";
import { dump } from "js-yaml";
import type { Language } from "../dora/event.js";
import { deploymentJob, smallTestsJob } from "./pr-pipeline.js";

export interface IntegrationPipelineOptions {
  service: string;
  team: string;
  language: Language;
}

/** Build the type-safe Integration Workflow (merge-to-main → validate → prod deploy). */
export function buildIntegrationPipeline(options: IntegrationPipelineOptions): Workflow {
  const validate = smallTestsJob(options.language);
  // The PR pipeline already promoted through Sandbox/Staging on the branch, so
  // the Integration pipeline deploys straight to Production.
  const deploy = deploymentJob(options.service, ["production"]).needs([validate]);

  return new Workflow(`${options.service}-integration`, {
    name: `${options.service} · Integration Pipeline`,
    on: { push: { branches: ["main"] } },
  }).addJobs([validate, deploy]);
}

/** Convenience: build + serialize to GitHub Actions YAML. */
export function generateIntegrationPipeline(options: IntegrationPipelineOptions): string {
  const wf = buildIntegrationPipeline(options);
  const header =
    `# GENERATED by @goldenpath/framework — do not edit by hand.\n` +
    `# Integration pipeline (merge to main) for ${options.service} (team: ${options.team}).\n`;
  return header + dump(wf.workflow, { lineWidth: 120, noRefs: true });
}
