/**
 * Amazon Q Developer automated PR-review workflow generator (bonus).
 *
 * Generates a GitHub Actions workflow that runs Amazon Q Developer's automated
 * code review on every pull request, using OIDC to assume an AWS role (no
 * long-lived secrets) and the Amazon Q Developer CLI to review the diff.
 *
 * This is a scaffold: it requires an AWS account with Amazon Q Developer enabled
 * and an IAM role trusting GitHub's OIDC provider (pass its ARN as `awsRoleArn`).
 */

import { NormalJob, Step, Workflow } from "github-actions-workflow-ts";
import { dump } from "js-yaml";

export interface QReviewOptions {
  service: string;
  /** ARN of the IAM role GitHub Actions assumes via OIDC. */
  awsRoleArn: string;
  awsRegion?: string;
}

export function buildQReviewWorkflow(options: QReviewOptions): Workflow {
  const region = options.awsRegion ?? "us-east-1";
  const review = new NormalJob("amazon-q-review", {
    name: "Amazon Q Developer Review",
    "runs-on": "ubuntu-latest",
    // OIDC: id-token to assume the AWS role; PRs need read + comment access.
    permissions: { "id-token": "write", contents: "read", "pull-requests": "write" },
  }).addSteps([
    new Step({ name: "Checkout", uses: "actions/checkout@v4", with: { "fetch-depth": "0" } }),
    new Step({
      name: "Configure AWS credentials (OIDC)",
      uses: "aws-actions/configure-aws-credentials@v4",
      with: { "role-to-assume": options.awsRoleArn, "aws-region": region },
    }),
    new Step({ name: "Install Amazon Q Developer CLI", run: "curl -fsSL https://desktop-release.q.us-east-1.amazonaws.com/latest/q-x86_64-linux.zip -o q.zip && unzip -q q.zip && ./q/install.sh --no-confirm && echo \"$HOME/.local/bin\" >> \"$GITHUB_PATH\"" }),
    new Step({
      name: "Run Amazon Q automated review on the PR diff",
      // Reviews the diff against the base branch and posts findings back to the PR.
      run: "q review --diff \"origin/${{ github.base_ref }}...HEAD\" --format github-pr",
      with: {},
    }),
  ]);

  return new Workflow(`${options.service}-q-review`, {
    name: `${options.service} · Amazon Q Review`,
    on: { pull_request: { branches: ["main"], types: ["opened", "synchronize", "reopened"] } },
  }).addJob(review);
}

/** Convenience: build + serialize to GitHub Actions YAML. */
export function generateQReviewWorkflow(options: QReviewOptions): string {
  const wf = buildQReviewWorkflow(options);
  const header =
    `# GENERATED by @goldenpath/framework — do not edit by hand.\n` +
    `# Amazon Q Developer automated PR review for ${options.service}.\n` +
    `# Requires: Amazon Q Developer enabled + an IAM role trusting GitHub OIDC.\n`;
  return header + dump(wf.workflow, { lineWidth: 120, noRefs: true });
}
