import { describe, expect, it } from "vitest";
import { buildEvent, buildPrPipeline, generatePrPipeline } from "../src/index.js";

// Small helper to read the raw job object the library builds.
function jobs(wf: ReturnType<typeof buildPrPipeline>) {
  return wf.workflow.jobs as Record<string, { needs?: string[]; steps: Array<{ name?: string; run?: string; uses?: string }> }>;
}

describe("PR pipeline generator (Stack-Aware, github-actions-workflow-ts)", () => {
  it("builds the two Golden Path stages: small-tests -> deployment", () => {
    const wf = buildPrPipeline({ service: "transactionify", team: "payments", language: "python" });
    const j = jobs(wf);
    expect(Object.keys(j)).toEqual(["small-tests", "deployment"]);
    expect(j.deployment!.needs).toContain("small-tests");
    expect(wf.workflow.on).toHaveProperty("pull_request");
  });

  it("selects language-specific test steps but keeps the same contract", () => {
    const stepsFor = (language: "python" | "go") => {
      const j = jobs(buildPrPipeline({ service: "s", team: "t", language }));
      return j["small-tests"]!.steps.map((s) => s.run ?? s.uses);
    };
    expect(stepsFor("python")).toContain("uv run pytest -q");
    expect(stepsFor("go")).toContain("go test ./... -count=1");
    // Contract stays identical across languages: both end with the standards check.
    expect(stepsFor("python").at(-1)).toBe("gp standards check");
    expect(stepsFor("go").at(-1)).toBe("gp standards check");
  });

  it("promotes through sandbox -> staging -> production and emits valid GHA YAML", () => {
    const yaml = generatePrPipeline({ service: "transactionify", team: "payments", language: "python" });
    expect(yaml).toContain("Deploy → sandbox");
    expect(yaml).toContain("Deploy → staging");
    expect(yaml).toContain("Deploy → production");
    expect(yaml).toContain("GENERATED by @goldenpath/framework");
    // Real GitHub Actions keys (the library guarantees these).
    expect(yaml).toContain("runs-on: ubuntu-latest");
    expect(yaml).not.toContain("runsOn");
  });
});

describe("DORA event contract", () => {
  it("produces a schema-shaped event with a SOC2 audit record", () => {
    const event = buildEvent({
      eventType: "deployment",
      workId: "FIN-123",
      actor: { id: "ci-bot", type: "machine" },
      service: { name: "transactionify", team: "payments", language: "python" },
      what: "deployed to production",
      timestamp: "2026-01-01T00:00:00.000Z",
      eventId: "evt-1",
      environment: "production",
      outcome: "success",
    });
    expect(event.schemaVersion).toBe("1.0.0");
    expect(event.source).toBe("ci");
    expect(event.audit).toEqual({
      who: "ci-bot",
      what: "deployed to production",
      when: "2026-01-01T00:00:00.000Z",
      why: "FIN-123",
    });
  });
});
